version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sistemas_distribuidos
      - DB_USER=root
      - DB_PASSWORD=root

  worker:
    build: ./workers
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sistemas_distribuidos
      - DB_USER=root
      - DB_PASSWORD=root

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistemas_distribuidos
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
